language: python
python: "3.5"
services: postgres
cache: pip

before_install:
  - pip install --upgrade pip
  - pip install codecov

install:
  - pip install -r requirements.txt
  - pip install git+https://github.com/joda-project/joda-backend-misc.git

script:
  - coverage run manage.py test

after_success:
  - codecov
