# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joda_core', '0002_default_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='sections',
            field=models.ManyToManyField(to='joda_core.Section'),
        ),
        migrations.AddField(
            model_name='file',
            name='sections',
            field=models.ManyToManyField(to='joda_core.Section'),
        ),
    ]
