# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 17:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djchoices.choices


class Migration(migrations.Migration):

    dependencies = [
        ('joda_core', '0003_sections_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'author', 'verbose_name_plural': 'authors'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'document', 'verbose_name_plural': 'documents'},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'file', 'verbose_name_plural': 'files'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'section', 'verbose_name_plural': 'sections'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'tag', 'verbose_name_plural': 'tags'},
        ),
        migrations.AlterModelOptions(
            name='usergroup',
            options={'verbose_name': 'user group', 'verbose_name_plural': 'user groups'},
        ),
        migrations.AddField(
            model_name='user',
            name='locale',
            field=models.CharField(default='en', max_length=5, verbose_name='locale'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='document',
            name='changed_at',
            field=models.DateTimeField(auto_now=True, verbose_name='changed at'),
        ),
        migrations.AlterField(
            model_name='document',
            name='changed_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='changed by'),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='document',
            name='files',
            field=models.ManyToManyField(to='joda_core.File', verbose_name='files'),
        ),
        migrations.AlterField(
            model_name='document',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='document',
            name='public',
            field=models.BooleanField(default=False, verbose_name='publicly visible'),
        ),
        migrations.AlterField(
            model_name='document',
            name='sections',
            field=models.ManyToManyField(to='joda_core.Section', verbose_name='sections'),
        ),
        migrations.AlterField(
            model_name='document',
            name='tags',
            field=models.ManyToManyField(blank=True, to='joda_core.Tag', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='document',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
        migrations.AlterField(
            model_name='file',
            name='changed_at',
            field=models.DateTimeField(auto_now=True, verbose_name='changed at'),
        ),
        migrations.AlterField(
            model_name='file',
            name='changed_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='changed by'),
        ),
        migrations.AlterField(
            model_name='file',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='file',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(choices=[('PDF', 'PDF'), ('JPEG', 'JPEG'), ('PNG', 'PNG')], editable=False, max_length=5, validators=[djchoices.choices.ChoicesValidator({'JPEG': 'JPEG', 'PDF': 'PDF', 'PNG': 'PNG'})], verbose_name='file type'),
        ),
        migrations.AlterField(
            model_name='file',
            name='label',
            field=models.CharField(blank=True, max_length=255, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='file',
            name='md5',
            field=models.CharField(editable=False, max_length=32, verbose_name='MD5'),
        ),
        migrations.AlterField(
            model_name='file',
            name='public',
            field=models.BooleanField(default=False, verbose_name='publicly visible'),
        ),
        migrations.AlterField(
            model_name='file',
            name='sections',
            field=models.ManyToManyField(to='joda_core.Section', verbose_name='sections'),
        ),
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.IntegerField(editable=False, verbose_name='size'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='remote_avatar',
            field=models.BooleanField(default=False, verbose_name='Gravatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_groups',
            field=models.ManyToManyField(to='joda_core.UserGroup', verbose_name='user groups'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='readable_sections',
            field=models.ManyToManyField(related_name='groups_can_read', to='joda_core.Section', verbose_name='visible sections'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='writable_sections',
            field=models.ManyToManyField(related_name='groups_can_write', to='joda_core.Section', verbose_name='editable sections'),
        ),
    ]
